tvkitchen/base

README.md, src/index.js, src/interfaces/IAppliance.js, src/interfaces/__test__/IAppliance.test.js, src/interfaces/__test__/classes/FullyImplementedAppliance.js, src/interfaces/__test__/classes/PartiallyImplementedAppliance.js, src/interfaces/__test__/classes/index.js, src/interfaces/index.js
This PR adds the `IAppliance` interface.  Since JavasScript doesn't actually support class abstraction and interface definition, we simulate these things by throwing errors if methods are not overridden by an appliance.
1. `yarn test`
None
Resolves #2 
Relies on PR #4 since it is based off of it; be sure to merge that first and rebase before merging this.
=> Create appliance interface

.editorconfig, .eslintrc, README.md, docs/DATA_TYPES.md, src/constants/__test__/dataTypes.test.js, src/constants/dataTypes.js, src/constants/index.js, src/index.js
This PR adds a list of data types which will be produced and consumed by appliances in the TV Kitchen.
It includes some tests that ensure the constants are named and populated according to standards -- these standards are part of the PR, so please feel free to push back on them if they don't feel right.
1. `yarn test`
None.
Resolves #7 
Related to PR #6 -- please do not merge this without merging that and rebasing.
=> Create data types constant file

docs/DATA_TYPES.md, packages/constants/src/dataTypes.js
This PR changes the name of the `STREAM.DATA` to be slightly more specific.
There was some exploration of the concept of getting even more concrete
with something along the lines of `STREAM.CONTAINER.MPEGTS` but since we
are not planning to support other types of containers in the near future
this felt like it would be more likely wrong than right.
1. `yarn test`
None
Resolves #14
=> Rename stream container data type

packages/classes/src/Payload.js, packages/classes/src/__test__/Payload.test.js, packages/classes/src/__test__/__snapshots__/Payload.test.js.snap
This PR fixes a bug where the Payload deserializer would break on objects containing null values.
1. `yarn test`
None
Resolves #18
=> Fix payload deserialization

docs/CONTRIBUTING.md, package.json, packages/classes/CHANGELOG.md, packages/classes/README.md, packages/classes/package.json, packages/constants/CHANGELOG.md, packages/constants/README.md, packages/constants/package.json, packages/errors/CHANGELOG.md, packages/errors/README.md, packages/errors/package.json, packages/interfaces/CHANGELOG.md, packages/interfaces/README.md, packages/interfaces/package.json
This PR prepares the repo for publishing to npm.
- Ensures we build the app before publishing
- Ensures we build the app before testing (which becomes redundant with the above, but is still safest)
- Reverts package version numbers to 0.0.0 so our first `lerna publish` process will work as expected
- Makes sure we publish both the original ES6 and transpiled files to npm
- Decorates each child package's `package.json` with repository and licensing info
- Adds a README for each child package (for completeness, and for rendering on npmjs.com)
Once this PR is merged into master, it should be safe to run `lerna publish` and away we go!
1. `yarn test`
Affects #13 but doesn't resolve it, since that will be a manual step
Relates to #11
=> Prepare repo for publishing to npm

packages/classes/CHANGELOG.md, packages/classes/package.json, packages/constants/CHANGELOG.md, packages/constants/package.json, packages/errors/CHANGELOG.md, packages/errors/package.json, packages/interfaces/CHANGELOG.md, packages/interfaces/package.json
In #13 we decided to publish directly to master (against my express advice, I'll note), which not only failed because of some missing settings, but had a series of [unforeseeable](https://www.youtube.com/watch?v=CJpQk6YAw1s) consequences. So, we're now moving safely to a branch to resolve pre-publishing issues and practice our first publish.
- Add the `publishConfig.access: "public"` setting to all packages; ensures our scoped packages are published as public
- Resolve some JSON formatting errors in package.json files
- Bumped version numbers to v1.0.0 and updated CHANGELOGs
1. `yarn test`
Affects #13
=> Publish v1.0.0 of all packages

.travis.yml, README.md, package.json
When using native Yarn Worskpaces instead of Lerna’s own monorepo management, the Lerna devs recommend not using the `bootstrap` command, since it does nothing more than reach down to native `yarn install`.
This PR removes the bootstrap-related code and updates the documentation. It also removes the explicit `yarn build` command from the setup instructions, since that’s covered (it turns out) by our `prepare` script.
1. `yarn test`
Resolves #21
=> Remove references to Lerna bootstrapping

docs/CONTRIBUTING.md
This PR repairs our CONTRIBUTING.md, which had broken links and misinformation from other projects.
- Fix links to other local files
- Remove misinformation about Sequelize / migrations
- Change our expressed whitespace preferences
- Remove links to TESTING and INSTALL docs, which we don't have (but probably should!)
- Add instructions to modify the CHANGELOG
None.
None.
Resolves #24
=> Fix CONTRIBUTING’s broken links and misinformation

packages/classes/CHANGELOG.md, packages/classes/package.json, packages/constants/CHANGELOG.md, packages/constants/package.json, packages/errors/CHANGELOG.md, packages/errors/package.json, packages/interfaces/CHANGELOG.md, packages/interfaces/package.json
Without a description, the somewhat awkwardly-worded first line of each project’s README is used in summarizing the package on npmjs.com, which doesn’t put our best foot forward.
This PR adds thoughtfully-composed short descriptions instead.
None
None
Resolves #28
=> Add descriptions to all package.json files

.github/pull_request_template.md
This PR updates our PR template to add a due diligence checklist item for updating the changelog. Which item is _not_ included below, since the PR is not merged, because that would be borrowing features from the future, which is not allowed.
None. Well, I suppose you could… well, no. There's no way to test it.
None.
Resolves #36
=> Add “changelog updated” item to PR template

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR adds `setup` and `teardown` methods to the IAppliance interface.  These methods are intended to provide a way for Appliance authors to prepare the appliance for processing and clean up after processing without being forced to do so in the appliance constructor.
1. `yarn test`
No
Resolves #41
=> Add setup and teardown methods to IAppliance

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js
The previous definition of invoke put the burden of looking up the
Payloads that it would process on the method itself. Similarly, it
required the `invoke` method to manage the internal state (either
directly or via method calls) to register Payloads that would need to be
re-processed.
By updating the `invoke` API, we are suggesting that that management
should occur outside of the `invoke` logic itself. It will be passed the
Payloads that it is being asked to process, and it will return the
Payloads that were not processed but still warrant future processing.
The change to parameters should not impact anybody who implemented using
the old API, though it is recommended that all future implementations of
`invoke` avoid managing the Appliance's internal Payload state directly.
The change to …
=> Update IAppliance invoke method

packages/constants/CHANGELOG.md, packages/constants/docs/LOG_LEVELS.md, packages/constants/src/__test__/logLevels.test.js, packages/constants/src/index.js, packages/constants/src/logLevels.js
As we seek to have consistant logging across the application, these log
levels should make it easier for Appliance developers to log
appropriately.
Issue #50
This PR adds log level constants for use in other parts of the system when logging.
1. `yarn test`
None
Resolves #50
=> Add log level constants

packages/interfaces/CHANGELOG.md, packages/interfaces/package.json, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js
Appliances are going to need to be able to log things, especially as we
work towards the concept of a method that verifies if an Appliance has
dependencies properly installed and outputs resolution instructions.
This adds a logger with an API that will work with
a [winston](https://www.npmjs.com/package/winston)  object.
Appliance developers should not assume that logger has been replaced,
and should only call the methods that are officially supported in the
IAppliance documentation.
Issue #48
This PR adds a default logger to IAppliance, which will allow Appliance developers to appropriately log in a way that can be collected by the TVKitchen.
1. `yarn test`
None
Resolves #48 
Related to #47
=> Add logger to IAppliance

packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR changes `audit` to be an async method, which was a mistake in the original PR for that method.
1. `yarn test`
None
Resolves #55
=> Make audit an async method

packages/classes/CHANGELOG.md, packages/classes/src/Payload.js, packages/classes/src/PayloadArray.js, packages/classes/src/__test__/Payload.unit.test.js, packages/classes/src/__test__/PayloadArray.unit.test.js
This PR adds static duck typing methods to the Payload and PayloadArray methods, which should help in cases where `instanceof` is unreliable.
1. `yarn test`
- None
Resolves #60
=> Add Payload and PayloadArray ducktypes

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js
This PR adds an IAppliance ducktype method, which makes it possible to determine if an object is an instance of `IAppliance` without relying on `instanceof`.
Note that since we cannot instantiate IAppliance directly, we had to create a helper "class" in order to use our getOwnPropertyNames short cut.  The alternative was to allow a special flag such as
`allowInterfaceInstantiation` that could be passed in as an overrideSetting, but I preferred the isolated code smell to something that would actually impact the API of IAppliance.
1. `yarn test`
None
Resolves #57
=> Add IAppliance duck typing

jest.config.json
Issue #53
This PR adds the `silent: true` option to the jest config.  Anybody who wants debug / console output when running tests can always use Jest's `--no-silent` flag when testing:
`yarn test --no-silent`
1. add a console.log or something to a test
2. `yarn test`
3 `yarn test --no-silent`
N/A
Resolves #53
=> Default to silent tests

packages/classes/CHANGELOG.md, packages/classes/src/Payload.js, packages/classes/src/__test__/Payload.unit.test.js, packages/classes/src/__test__/__snapshots__/Payload.unit.test.js.snap
This PR changes the default value of `createdAt` for new `Payload` objects so that it is set to whatever the current time's ISO string is at the time of construction.
1. `yarn test`
None
Resolves #62
=> Update Payload createdAt default value

packages/constants/CHANGELOG.md, packages/constants/docs/APPLIANCE_EVENTS.md, packages/constants/src/__test__/applianceEvents.test.js, packages/constants/src/applianceEvents.js, packages/constants/src/index.js
This PR adds appliance event constants, which will be used by appliance implementations to send events in addition to being used by the TV Kitchen to handle those events.
1. `yarn test`
None
Resolves #65
=> Add appliance event constants

lerna.json, package.json, yarn.lock
This PR Removes Lerna.  We were only using it for the build step right now, which yarn can handle across all packages perfectly well.
We may want to add it back some day as part of #11, but no need to add it until then.
1. `yarn test`
- `yarn install`
Resolves #39 
Related to #11
=> Remove lerna

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR removes the implementation-level `emitResult` method from `IAppliance`.
`emitResult` was always documented as an internal helper method, but since IAppliance did not actually use it, it did not belong at the interface level.
IAppliance should really only be defining the external API -- for anybody *using* an Appliance. `emitResult` was a method for an Appliance implementor, which means it belongs in `AbstractAppliance` instead.
1. `yarn test`
None
Resolves #67
=> Remove emitResult from IAppliance

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR converts the getInputType and getOutputType methods of IAppliance were originally
defined as being instance methods.
1. `yarn test`
None
Resolves #77
=> Convert type lookup methods to static methods

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR changes the `setup` and `teardown` methods of IAppliance to `start` and `stop`.
1. `yarn test`
- This is a breaking change.
Resolves #79
=> Rename IAppliance setup / teardown

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js, packages/interfaces/src/__test__/IAppliance.test.js, packages/interfaces/src/__test__/classes/FullyImplementedAppliance.js
This PR changes IAppliance to make it function as a stream instead of a simple event emitter.  This is a significant change for Appliances and will require modification to AbstractAppliance in order to have it conform to the new model.
Existing appliances will also need to be modified to use things like `this.push` to write new payloads.
1. `yarn test`
Resolves #88 
This includes #89, so please wait to review this until after that plus rebase.
=> Make IAppliance a Transform stream

packages/classes/CHANGELOG.md, packages/classes/docs/PAYLOAD.md, packages/classes/src/Payload.js, packages/classes/src/__test__/Payload.unit.test.js
This PR adds getter / setter helpers to the `Payload` base class, making it a bit easier to work with the `data` attribute of a payload.
- This represents a minor patch.
Resolves #96
=> Add Payload data helpers

packages/classes/CHANGELOG.md, packages/classes/docs/PAYLOAD_ARRAY.md, packages/classes/src/PayloadArray.js, packages/classes/src/__test__/PayloadArray.unit.test.js
This PR adds several methods making it easy to access the time values associated with a PayloadArray
This represents a minor patch
Resolves #95
=> Add PayloadArray time methods

package.json, yarn.lock
This PR adds a cleanup step when building.
This is part of issue #114 since it's part of improving our build processes to support TypeScript
=> Run rimraf on build

packages/interfaces/CHANGELOG.md, packages/interfaces/src/IAppliance.js
This PR fixes an issue where the `_transform` method was not returning the promise.  In more recenve versions of NodeJS this was resulting in the stream callback being called more than once, creating an error.
Resolves #124
=> Return a promise in _transform
